should also look into headers for input_size
JuliaLang/Downloads.jl pull request #167
Opened 2021-12-08 06:10 UTC by tanmaykm

If no content length is set while uploading some contents, Curl defaults to use chunked transfer encoding. In some cases we want to prevent that because the server may not be supporting chunked transfers (and we already know the size).

With this change, the request method will also look at the headers while determining the input size and if found call `set_upload_size` as usual. So to switch off chunked transfers, one must also know and set the content length header while invoking `download` or `request` methods.

2021-12-09 16:39 UTC, StefanKarpinski requested changes
Minor tweaks but otherwise looks good to me.

2021-12-09 16:39 UTC, StefanKarpinski commented on src/Downloads.jl
> +function content_length(headers)
```suggestion
function content_length(headers::Union{AbstractVector, AbstractDict})
```
I like to clarify the type even on helper definitions like this (mostly just for documentation).

2021-12-09 16:39 UTC, StefanKarpinski commented on src/Downloads.jl
> +    for kv in headers
This would be clearer imo with destructuring into `(key, value)`.

2021-12-09 16:39 UTC, StefanKarpinski commented on src/Downloads.jl
> +        # take input_size from content-length header is one is supplied
```suggestion
        # take input_size from content-length header if one is supplied
```

2021-12-10 02:34 UTC, tanmaykm commented on src/Downloads.jl
> +    for kv in headers
:+1: done in https://github.com/JuliaLang/Downloads.jl/pull/167/commits/f4cdcb509ad4562dd2bf522ccc60e4067dd5b107

2021-12-13 15:25 UTC, StefanKarpinski commented on src/Downloads.jl
> +    for (key,value) in headers
```suggestion
    for (key, value) in headers
```

2021-12-13 15:27 UTC, StefanKarpinski approved these changes

2021-12-13 16:21 UTC, merged