dont set Curl option TCP_FASTOPEN
JuliaLang/Downloads.jl pull request #76
Opened 2020-11-25 22:17 UTC by KlausC

fixes #36

2020-11-25 22:25 UTC, giordano commented
Maybe add tests in #45?

2020-11-26 14:16 UTC, KlausC commented
An upstream bug has been reported here: https://github.com/curl/curl/issues/6252

2020-11-27 19:03 UTC, StefanKarpinski commented
Setting TCP_FASTOPEN significantly speeds up HTTP downloads. Perhaps this should be changed to only not set TCP_FASTOPEN when doing an FTP download on Linux since that's the only place where this causes issues?

2020-11-27 19:05 UTC, StefanKarpinski commented
Or if we're not going to set the option, it would be better to just delete the call entirely since not setting it is the default and in general using the default should be safe.

Thanks a lot for finding the cause of this problem, by the way!

2020-11-27 19:08 UTC, StefanKarpinski requested changes

2020-11-27 19:08 UTC, StefanKarpinski commented on src/Curl/Easy.jl
> +    curl_easy_setopt(easy.handle, CURLOPT_TCP_FASTOPEN, false) # upstream error
```suggestion
```
If we're not going to set the option, we can just delete this line entirely.

2020-11-27 19:08 UTC, StefanKarpinski commented on test/runtests.jl
> +@testset "ftp download" begin
```suggestion
@__MODULE__ == Main && @testset "ftp download" begin
```
This will not run this test suite during Julia CI (which generates an anonymous module that it runs each test suite in). It's fine to use a random FTP server for CI for this package by itself but Julia CI runs so much that it will surely cause problems and flakiness.

2020-11-29 18:36 UTC, StefanKarpinski approved these changes
I have applied the changes that I requested. Will merge when CI passes.

2020-11-29 19:17 UTC, merged

2020-12-06 10:38 UTC, KlausC commented
> An upstream bug has been reported here: [curl/curl#6252](https://github.com/curl/curl/issues/6252)

As of 2020/12/6 upstream fix has been merged into master. Will probably be in coming release curl-7.74

2020-12-06 14:44 UTC, StefanKarpinski commented
👍🏻 I'm also following those issues — thanks for making the upstream fix! If you happen to notice when the release is made, ping me and I'll see about making this set `TCP_FASTOPEN` if the libcurl version is new enough.

2020-12-17 16:32 UTC, KlausC commented
The upstream project issued release 7.74 recently, including the fix mentioned above.

 https://curl.se/download.html